services:
  - name: youtube-transcript-app
    ports:
      - port: 8000
        http: {}
    routes:
      - path: /
        port: 8000
    env:
      - key: PORT
        value: "8000"
    scalings:
      min: 1
      max: 1
    build:
      command: |
        pip install -r requirements.txt
      run: |
        gunicorn app:app --bind 0.0.0.0:$PORT
